package clojure.lang;

public class ArityException extends IllegalArgumentException {
  public final int actual;
  
  public final String name;
  
  public ArityException(int actual, String name) { this(actual, name, null); }
  
  public ArityException(int actual, String name, Throwable cause) {
    super("Wrong number of args (" + actual + ") passed to: " + Compiler.demunge(name), cause);
    this.actual = actual;
    this.name = name;
  }
}
